### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-css-flexbox-and-columns#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://nosy-toothpaste.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/css-flexbox-and-columns/1) criteria:
- [x] The text in the "Join A Game section" should flow into two columns, because it'll be a lot longer in the real website
- [x] The games in the "Top Games" section show 3 games per row, though there may be up to 9, so if there are more than 3, there should be 3 per line
- [x] The "Search Games" input should always be the same size (about 300 pixels wide maybe?)
- [x] In the "Create A Game" section, the list should always take up half the space and the "Create Your Own Game" button should take up the other half

**Comment by chrisvfritz** [comment]
You overachiever, with your media queries and excellent use of HTML5 semantic elements. :stuck_out_tongue_winking_eye: :tada: :shipit:
